const menu = [
	{
		id: 1,
		title: 'buttermilk pancakes',
		category: 'breakfast',
		price: 15.99,
		img: '/images/item-1.jpeg',
		desc: `Fluffy buttermilk pancakes served with a choice of maple syrup or fruit compote. Perfect for a hearty breakfast.`,
	},
	{
		id: 2,
		title: 'diner double',
		category: 'lunch',
		price: 13.99,
		img: '/images/item-2.jpeg',
		desc: `A classic diner-style double cheeseburger with lettuce, tomato, and special sauce. Served with fries.`,
	},
	{
		id: 3,
		title: 'godzilla milkshake',
		category: 'shakes',
		price: 6.99,
		img: '/images/item-3.jpeg',
		desc: `A monstrous milkshake with layers of chocolate, caramel, and whipped cream. Topped with a cherry.`,
	},
	{
		id: 4,
		title: 'country delight',
		category: 'breakfast',
		price: 20.99,
		img: '/images/item-4.jpeg',
		desc: `A hearty breakfast platter with eggs, bacon, sausage, and toast. A true country-style feast.`,
	},
	{
		id: 5,
		title: 'egg attack',
		category: 'lunch',
		price: 22.99,
		img: '/images/item-5.jpeg',
		desc: `A savory lunch option featuring a fried egg on a bed of greens with avocado and tomato. Light yet satisfying.`,
	},
	{
		id: 6,
		title: 'oreo dream',
		category: 'shakes',
		price: 18.99,
		img: '/images/item-6.jpeg',
		desc: `A dreamy milkshake blended with Oreo cookies and vanilla ice cream. Garnished with cookie crumbs.`,
	},
	{
		id: 7,
		title: 'bacon overflow',
		category: 'breakfast',
		price: 8.99,
		img: '/images/item-7.jpeg',
		desc: `Crispy bacon strips served with scrambled eggs and toast. A simple yet delicious start to the day.`,
	},
	{
		id: 8,
		title: 'american classic',
		category: 'lunch',
		price: 12.99,
		img: '/images/item-8.jpeg',
		desc: `A traditional American lunch with a grilled cheese sandwich and tomato soup. Comfort food at its best.`,
	},
	{
		id: 9,
		title: 'quarantine buddy',
		category: 'shakes',
		price: 16.99,
		img: '/images/item-9.jpeg',
		desc: `A comforting milkshake with flavors of peanut butter and banana. Perfect for a cozy day in.`,
	},
];
export default menu;
